### ISSUE TITLE
Error coming while executing main.py

### ISSUE THREAD

**Issue by kevalpattani** [mebinthattil/Hostel-Wifi-Login-Automation#1]
-Wifi-Login-Automation-main/main.py
Your chrome driver was not found
Traceback (most recent call last):
  File "/home/keval/Downloads/Hostel-Wifi-Login-Automation-main/login.py", line 18, in <module>
    driver.get("http://172.16.1.1:8090/")
    ^^^^^^
NameError: name 'driver' is not defined. Did you mean: 'webdriver'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/keval/Downloads/Hostel-Wifi-Login-Automation-main/main.py", line 7, in <module>
    import login
  File "/home/keval/Downloads/Hostel-Wifi-Login-Automation-main/login.py", line 26, in <module>
    driver.quit()
    ^^^^^^
NameError: name 'driver' is not defined. Did you mean: 'webdriver'?  

this is the error

**Comment by kevalpattani** [comment]
I am using Linux
